version: '3.8'
services:
  tarmac-example:
    image: madflojo/tarmac:unstable
    ports:
      - 80:8080
    environment:
      - "APP_ENABLE_TLS=false"
      - "APP_LISTEN_ADDR=0.0.0.0:8080"
      - "APP_DEBUG=true"
      - "APP_ENABLE_KVSTORE=true"
      - "APP_KVSTORE_TYPE=redis"
      - "APP_REDIS_SERVER=redis:6379"
    volumes:
      - "./functions:/functions"
    depends_on:
      - redis
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
